server:
  port: 8088
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: htttp://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
ly:
  jwt:
    secret: ly@Login(Auth}*^31)&heiMa% # 登录校验的密钥
    pubKeyPath: D:/heima/rsa/rsa.pub # 公钥地址
    priKeyPath: D:/heima/rsa/rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN #cookie名