server:
  port: 8082

spring:
  application:
    name: item-service
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/yun6?&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  rabbitmq:
      host: 192.168.198.132
      username: leyou
      password: leyou
      virtual-host: /leyou
      template:
        retry:
          enabled: true
          initial-interval: 10000ms
          max-interval: 300000ms
          multiplier: 2
        exchange: ly.item.exchange #默认交换机
      publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
#mybatis日志
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
