server:
  port: 8085
spring:
  application:
    name: page-service
  main:
      allow-bean-definition-overriding: true
  rabbitmq:
      host: 192.168.198.132
      username: leyou
      password: leyou
      virtual-host: /leyou
thymeleaf:
  cache: false
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}.${server.port}