server:
  port: 8087
spring:
  application:
    name: user-service
  datasource:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/yun6?&useSSL=false&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 30
        minimum-idle: 10
  rabbitmq:
    host: 192.168.198.132
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.198.132
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10

mybatis:
  type-aliases-package: com.leyou.item.pojo